version: '3.8'

services:
  backend:
    container_name: backend
    image: nmngo248/kanji-back:0.0.1-SNAPSHOT
    hostname: backend
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - neo

  neo:
    image: neo4j:latest
    container_name: neo
    hostname: neo
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j/data:/data

networks:
  default:
    name: kanji-network
