type Query {
    findUserByUsername(username: String!): User
    findAllUsers(pageNum: Int!, pageSize: Int!): [User]!
    findKanjiByValue(value: String!): Kanji
    findKanjiByJlpt(value: Int!): [Kanji]!
}

type Mutation {
    createUser(username: String!, password: String!, jlpt: Int): User!
    createKanji(value: String!, stroke: Int, grade: Int, frequency: Int, jlpt: Int, meaning: [String]!, readings_on: [String], readings_kun: [String]): Kanji!
    userLearntKanji(username: String!, kanji: String!): User!
    login(username: String!, password: String!): AuthenticationResponse!
}

type User {
    id: ID!
    username: String!
    role: String!
    jlpt: Int
    LEARNT_KANJI: [Kanji]
    LEARNT_VOCABULARY: [Vocabulary]
}

type Kanji {
    id: ID!
    value: String!
    stroke: Int
    grade: Int
    frequency: Int
    jlpt: Int
    meaning: [String]!
    readings_on: [String]!
    readings_kun: [String]!
    PART_OF: [Vocabulary]
}

type Vocabulary {
    id: ID!
    original: String!
    furigana: [String]!
    meaning: [String]!
    jlpt: Int
}

type AuthenticationResponse {
    jwt: String!
    id: String!
    username: String!
    role: String!
}
