type Query {
    # User
    findUserByUsername(username: String!): User
    findAllUsers(paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [User]!
    # Kanji
    findKanjiByValue(value: String!): Kanji
    findKanjiByJlpt(jlpt: Int!, paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [Kanji]!
    findKanjiByStrokes(strokes: Int!, paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [Kanji]!
    findKanjiByGrade(grade: Int!, paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [Kanji]!
    # Vocabulary
    findVocabularyByOriginal(original: String!): Vocabulary
    findVocabularyByJlpt(jlpt: Int!, paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [Vocabulary]!
    findVocabularyByFurigana(furigana: String!, paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [Vocabulary]!
    findVocabularyByMeaning(meaning: String!, paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [Vocabulary]!
    findAllVocabulary(paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [Vocabulary]!
    # KanjiResult
    findBestShouldLearnKanji(username: String!, paginationInput: PaginationInput = {pageNum: 0, pageSize: 10, ordering: ASC}): [KanjiResult]!
}

type Mutation {
    createUser(username: String!, password: String!, jlpt: Int): User!
    createKanji(value: String!, strokes: Int, grade: Int, frequency: Int, jlpt: Int, meaning: [String]!, readings_on: [String], readings_kun: [String]): Kanji!
    createVocabulary(original: String!, furigana: [String]!, meaning: [String]!, jlpt: Int): Vocabulary!
    userLearntKanji(username: String!, kanji: String!): User!
    login(username: String!, password: String!): AuthenticationResponse!
}

enum Ordering {
    ASC
    DESC
}

input PaginationInput {
    pageNum: Int!
    pageSize: Int!
    ordering: Ordering!
}

type User {
    id: ID!
    username: String!
    role: String!
    jlpt: Int
    LEARNT_KANJI: [Kanji]
    LEARNT_VOCABULARY: [Vocabulary]
}

type KanjiResult {
    kanji: Kanji!,
    occurrence: Int!
}

type Kanji {
    id: ID!
    value: String!
    strokes: Int
    grade: Int
    frequency: Int
    jlpt: Int
    meaning: [String]!
    readings_on: [String]
    readings_kun: [String]
    PART_OF: [Vocabulary]
}

type Vocabulary {
    id: ID!
    original: String!
    furigana: [String]!
    meaning: [String]!
    jlpt: Int
}

type AuthenticationResponse {
    jwt: String!
    id: String!
    username: String!
    role: String!
}
