spring:
  application:
    name: learn-kanji
  neo4j:
    uri: bolt://neo:7687
    authentication:
      username: neo4j
      password: password
    pool:
      metrics-enabled: true
  graphql:
    # Enable GraphQL UI
    graphiql:
      enabled: true
    path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always