spring:
  application:
    name: learn-kanji
  main:
    allow-bean-definition-overriding: true
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
    pool:
      metrics-enabled: true
  graphql:
    # Enable GraphQL UI
    graphiql:
      enabled: true
    path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}

org:
  neo4j:
    migrations:
      locations-to-scan: classpath:db/migrations

logging:
  level:
    org.springframework.data.repository: DEBUG
    org.springframework.data.neo4j: DEBUG
    org.springframework.data.neo4j.cypher.unrecognized: OFF
    org.neo4j.migrations: DEBUG