spring:
  application:
    name: learn-kanji
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
    pool:
      metrics-enabled: true
  graphql:
    # Enable GraphQL UI
    graphiql:
      enabled: true
    path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

org:
  neo4j:
    migrations:
      locations-to-scan: classpath:neo4j/migrations

logging:
  level:
    org.springframework.data.repository: DEBUG
    org.springframework.data.neo4j: DEBUG
    org.springframework.data.neo4j.cypher.unrecognized: OFF
    org.neo4j.migrations: DEBUG